### ISSUE TITLE
Have the bot leave the channel after it plays the sound

### ISSUE THREAD

**Issue by lolSam** [thibautbessone/DiscordBlueBot#2]
Would it be possible to add an option to have the bot leave the channel once it's done playing the sound? Would be great! Love the bot 👍

**Comment by thibautbessone** [comment]
This will probably be added in the next updates, I'm going to add more option to the sound system. This will be writed in commits and will probably have its own release here. I'll also close this issue when it's done - Thanks for using the bo, I'm glad you like it !

**Comment by thibautbessone** [comment]
Actually, after looking into it, this will probably not be implemented to avoid flooding the API (and the server) with open/close audio connections requests. A future implementation isn't totally excluded, but at this time the development of this functionnality is discontinued
